services:
  - type: web
    name: data-science-hub-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 7d
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 5000

databases:
  - name: data-science-hub-db
    databaseName: data_science_hub
    plan: free 